package com.miHoYo.GenshinImpa.util

object Util {
    const val ONESIGNAL_APP_ID = ">5161c322-f8e8-430d-88c8-b4d7776c18b5"
    val mtKey = "96287175403510526159"
    val myId: String = "myID"
    var instId: String? = "instID"
    var urlMain: String = "link"
    var linkaa: String = "link"
    var apps: String = "apps"
    var MAIN_ID: String? = "main_id"
    var aps_id: String? = "main_id"
    val keyVAl = "tdb2"
    var C1: String? = "c11"
    const val myTrId = ""
    val appsCheckChe: String = "appsCheckChe"
    val geoCo: String = "country"
    val codeCode: String = "uff"
    val deepL: String = "deepL"
    var defaultValue = "null"
    val one = "deviceID="
    val subOne = "sub_id_1="
    val ad_id = "ad_id="
    val subFour = "sub_id_4="
    val subFive = "sub_id_5="
    val subSix = "sub_id_6="
    val namm = "naming"
    val trololo = "deeporg"
}